tasks:
  - before: cd /home/gitpod/.nvm/versions/node/v12.19.0/lib/node_modules/node-red/ && npm link /workspace/openapi-red/ && cd /workspace/openapi-red/
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - svelte.svelte-vscode@104.0.0:bCbDpi01c0Qt+pqOeQV7Sw==